#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wizarr"
name = "Wizarr"
description.en = "Media server invitation system with custom wizard steps for Plex, Jellyfin, Emby and more"
description.fr = "Système d'invitation pour serveurs multimédias avec des étapes d'assistant personnalisées pour Plex, Jellyfin, Emby et plus"

version = "2025.7.5b~ynh1"

maintainers = ["botagas"]

[upstream]
license = "MIT"
website = "https://github.com/Wizarrrr/wizarr"
demo = "https://demo.wizarr.dev"
admindoc = "https://docs.wizarr.dev"
userdoc = "https://docs.wizarr.dev"
code = "https://github.com/Wizarrrr/wizarr"
cpe = "cpe:2.3:a:wizarr:wizarr"

# This is meant to be an URL where people can financially support this app, especially when its development is based
# on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.
fund = "https://github.com/sponsors/Wizarrrr"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
# Python 3.13 compilation requires modern architectures
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "200M"
ram.build = "1G"
ram.runtime = "200M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

    [install.admin_username]
    type = "user"
    help.en = "Username for Wizarr admin account (3-15 characters)"
    
    [install.admin_password]
    type = "password"
    ask.en = "Admin password"
    help.en = "Password must be at least 8 characters with uppercase, lowercase, and number"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Wizarrrr/wizarr/archive/refs/tags/2025.7.5b.tar.gz"
    sha256 = "2c00860c5debf0a6442c712275f7d25904c151369d137d75844291eaa23901c0"
    
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    main.default = 5690

    [resources.apt]
    # Build dependencies for Python compilation, UV, and Node.js
    packages = [
        "build-essential",
        "libssl-dev", 
        "zlib1g-dev",
        "libbz2-dev",
        "libreadline-dev", 
        "libsqlite3-dev",
        "wget",
        "curl",
        "llvm",
        "libncurses5-dev",
        "xz-utils",
        "tk-dev",
        "libxml2-dev",
        "libxmlsec1-dev", 
        "libffi-dev",
        "liblzma-dev",
        "python3-dev",
        "python3-pip",
        "python3-venv",
        "pipx"
    ]
