#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

# Backup the NGINX configuration
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

# Backup the systemd service unit
ynh_backup "/etc/systemd/system/$app.service"

# Backup the logrotate configuration
# ynh_backup "/etc/logrotate.d/$app"
# Note: Log files are not backed up as they will be recreated on restore


# Backup Python installation (if it's our custom version)
if [ -f "/usr/local/bin/python$py_vshort" ]; then
    ynh_backup "/usr/local/bin/python$py_vshort"
    ynh_backup "/usr/local/lib/python$py_vshort"
    ynh_backup "/etc/ld.so.conf.d/python3.13.conf"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
