#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### - $install_dir
### - $port
### ...

### For remove operations:
### - the core will deprovision every resource defined in the manifest **after** this script is ran
### this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_logrotate

# Remove Node.js
ynh_nodejs_remove

# Remove custom Python installation
uninstall_python $py_version

# Remove UV package manager
uninstall_uv

# Remove application-specific files
ynh_safe_rm "/etc/ld.so.conf.d/python3.13.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
